"""Tables the ORM no longer declares must be shielded from autogenerate.

`alembic revision --autogenerate` compares the ORM metadata against the live
database and emits `op.drop_table(...)` for anything it finds in the database
but not in the models. `alembic/env.py` guards against that with an
`include_name` filter over `_LEGACY_TABLES`.

`cross_engine_synthesis` and `multi_engine_backtest_runs` were created by
migrations that are now archived, orphaned by the 2026-07 cross-engine strip,
and still present on any database built before the squash. Left out of the
filter, the next unrelated autogenerated migration would carry a silent DROP for
both.

env.py cannot be imported standalone — it reads `context.config` at module level
and only works under an alembic run — so the set is read out of the source with
ast rather than executed.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

ENV_PY = Path(__file__).resolve().parents[2] / "alembic" / "env.py"


def _legacy_tables() -> set[str]:
    tree = ast.parse(ENV_PY.read_text())
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        if not any(
            isinstance(t, ast.Name) and t.id == "_LEGACY_TABLES" for t in node.targets
        ):
            continue
        # frozenset({...})
        call = node.value
        assert isinstance(call, ast.Call), "_LEGACY_TABLES should be frozenset({...})"
        return {
            el.value
            for el in call.args[0].elts
            if isinstance(el, ast.Constant) and isinstance(el.value, str)
        }
    raise AssertionError("_LEGACY_TABLES not found in alembic/env.py")


@pytest.mark.parametrize(
    "table", ["cross_engine_synthesis", "multi_engine_backtest_runs"]
)
def test_cross_engine_orphans_are_shielded(table: str) -> None:
    assert table in _legacy_tables(), (
        f"{table} exists on pre-squash databases but not in the ORM. Without it "
        "in _LEGACY_TABLES, autogenerate will write a DROP TABLE for it into the "
        "next migration."
    )


def test_the_original_legacy_entries_are_still_there() -> None:
    """Adding to the set must not become an accidental replacement of it."""
    assert {
        "daily_market_data",
        "paper_trades",
        "tickers",
        "screener_signals",
        "reversion_signals",
    } <= _legacy_tables()


def test_shielded_tables_are_not_declared_by_the_orm() -> None:
    """A table in both places would be shielded from real schema changes."""
    from src.db.models import Base

    overlap = _legacy_tables() & set(Base.metadata.tables)
    assert not overlap, (
        "these are shielded from autogenerate but ARE ORM-managed, so real "
        f"changes to them would be silently skipped: {sorted(overlap)}"
    )
