"""Measurement plumbing: shadow-booked gate blocks + live drift monitoring.

Two Tier-0 items from the 2026-08 strategy review, both about making existing
failures VISIBLE rather than changing what the book trades:

1. Picks the validation gate blocks were deleted before persistence, so the two
   2026-07 outages left zero record of foregone P&L and the gate's demonstrated
   failure mode (blocking healthy models on small-n noise) was unmeasurable.
2. The nightly drift monitor queried a table belonging to engines scaled to zero
   in 2026-03, against the retired 71.6%-WR baseline — a silent nightly no-op.
"""
from __future__ import annotations

import pytest

# Reuse the JSONB->JSON sqlite shim registered by the persistence test module.
from tests.test_db import test_exit_config_persistence  # noqa: F401

from src.output.performance import SHADOW_SKIP_REASON
from src.research.drift_check import (
    BASELINES,
    DRIFT_SHORTFALL_PCT,
    MIN_TRADES_TO_JUDGE,
    DriftReport,
    StreamDrift,
    format_drift_report,
)


# ── Shadow-booking ─────────────────────────────────────────────────────────

def test_shadow_skip_reason_fits_the_column():
    """Outcome.skip_reason is String(30) — a longer label would truncate or raise."""
    assert len(SHADOW_SKIP_REASON) <= 30


# NOTE: the SQL behaviour these used to assert by grepping function source now
# has real DB-backed coverage in tests/test_db/test_shadow_and_candidates.py —
# a source grep passes whether or not the query is correct, which is exactly the
# failure mode it was meant to guard against.


def test_shadow_rows_are_excluded_from_stats_by_the_existing_convention():
    """Every stats query filters `skip_reason.is_(None)`. Shadow rows carry a
    non-null reason, so they are excluded for free — that is the whole reason
    this label was chosen over a new column."""
    assert SHADOW_SKIP_REASON is not None
    assert SHADOW_SKIP_REASON != ""






# ── Drift monitor ──────────────────────────────────────────────────────────

def test_retired_mr_and_pead_baselines_cannot_drive_drift_alerts():
    """September research retired these point estimates. Null keeps each stream
    visible without drawing or alerting against numbers we no longer believe."""
    for key in (
        "mean_reversion|mas_official", "mean_reversion|mr_shadow",
        "mean_reversion|mr_manual_sleeve",
        "pead|pead_paper", "pead|pead_neglected", "pead|pead_60d_shadow",
    ):
        assert BASELINES[key]["wr"] is None
        assert BASELINES[key]["avg"] is None


def test_drift_covers_every_live_stream():
    """A stream with no baseline is reported but never alerts, so a missing key
    silently disables monitoring for it."""
    for key in ("sniper|mas_official", "sniper|sniper_shadow", "mean_reversion|mas_official",
                "mean_reversion|mr_shadow",
                "pead|pead_paper", "pead|pead_neglected", "pead|pead_60d_shadow"):
        assert key in BASELINES


def test_drift_does_not_alert_below_the_sample_floor():
    """Small-n over-reaction is this project's recurring gate failure; the
    monitor must not repeat it."""
    assert MIN_TRADES_TO_JUDGE >= 15


def test_drift_shortfall_threshold_is_loose_enough_to_avoid_noise():
    assert 0.0 < DRIFT_SHORTFALL_PCT <= 0.6


def test_report_renders_and_flags_alerting_streams():
    r = DriftReport(
        lookback_days=30, total_resolved=25,
        streams=[
            StreamDrift(stream="sniper|mas_official", label="Sniper (official)", n=20,
                        live_win_rate=0.55, live_avg=0.10, baseline_avg=0.54,
                        baseline_wr=0.543, alerts=["degraded"]),
            StreamDrift(stream="mean_reversion|mas_official", label="MR (official)", n=5,
                        live_win_rate=0.60, live_avg=0.50, baseline_avg=0.46,
                        baseline_wr=0.522),
        ],
        alerts=["degraded"],
    )
    out = format_drift_report(r)
    assert "Sniper (official)" in out and "MR (official)" in out
    assert "ALERTS (1)" in out
    # the healthy stream must not be flagged
    mr_line = [ln for ln in out.splitlines() if "MR (official)" in ln][0]
    assert not mr_line.rstrip().endswith("!")


def test_report_says_so_when_nothing_drifted():
    r = DriftReport(lookback_days=30, total_resolved=40, streams=[], alerts=[])
    assert "No drift detected" in format_drift_report(r)


@pytest.mark.asyncio
async def test_paired_observations_do_not_release_another_streams_drift_alert():
    """`total_resolved` gates whether ANY drift alert is sent (main.py, >= 10).

    The paired stream has a null baseline so it can never raise an alert of its
    own — but counting it could push the total over the threshold and release
    an alert generated by a different stream. It is not an additional trade.
    """
    from datetime import date, timedelta
    from unittest.mock import patch
    from contextlib import asynccontextmanager

    from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

    from src.db.models import Base, Outcome, Signal
    from src.research import drift_check

    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    factory = async_sessionmaker(engine, expire_on_commit=False)

    d = date.today() - timedelta(days=2)
    async with factory() as s:
        for i in range(6):
            source = "pead_paper" if i < 3 else "pead_60d_shadow"
            s.add(Signal(
                id=i + 1, run_date=d, ticker=f"T{i}", direction="LONG",
                signal_model="pead", signal_source=source,
                entry_price=100.0, stop_loss=97.0, target_1=106.0,
                holding_period_days=20, confidence=80.0,
                risk_gate_decision="APPROVE", regime="bull",
            ))
            s.add(Outcome(
                signal_id=i + 1, ticker=f"T{i}", entry_date=d, entry_price=100.0,
                exit_date=d, exit_price=101.0, exit_reason="target",
                pnl_pct=1.0, still_open=False,
            ))
        await s.commit()

    @asynccontextmanager
    async def _fake_session():
        async with factory() as session:
            yield session

    with patch.object(drift_check, "get_session", _fake_session):
        report = await drift_check.compute_drift(lookback_days=30)

    assert report.total_resolved == 3, "paired rows must not count as trades"
    assert all("60d_shadow" not in st.stream for st in report.streams)
