"""baseline schema — every table the ORM declares

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-10

This is the squashed root of the migration history.

Why it exists
-------------
The previous root (`e9b5089b0025`, Feb 2026) was autogenerated against a
database that `Base.metadata.create_all` had already built, so it opened with a
foreign key to `signals.id` without ever creating `signals`. Nine core tables —
signals, outcomes, daily_runs, candidates, agent_logs, pipeline_artifacts,
divergence_events, divergence_outcomes, near_misses — were never created by any
migration at all. `alembic upgrade head` against an empty database therefore
failed with `UndefinedTableError: relation "signals" does not exist`, and the
production schema was not reproducible from source.

This baseline creates the full ORM schema in one step. The sixteen historical
migrations are retained under `alembic/archive/` for provenance; they are not on
the version path and are never executed.

Existing databases
------------------
A database already at the old head (`1c2d3e4f5a6b`) has this exact schema and
needs no action: that id remains on the version path as a no-op successor to
this revision (see `1c2d3e4f5a6b_bridge_from_pre_squash_history.py`), so
`alembic upgrade head` finds it already at head. Note that long-lived databases
additionally carry
`cross_engine_synthesis` and `multi_engine_backtest_runs`, left behind by the
2026-07 cross-engine strip. No code reads them and the ORM does not declare
them, so the baseline does not create them; the stamp asserts that the
baseline's tables are present and correctly shaped, not that nothing else is.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the full schema."""
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_run_date'), 'agent_logs', ['run_date'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('avg_daily_volume', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('signal_model', sa.String(length=30), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_run_date'), 'candidates', ['run_date'], unique=False)
    op.create_index(op.f('ix_candidates_ticker'), 'candidates', ['ticker'], unique=False)
    op.create_table('daily_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('regime_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('candidates_scored', sa.Integer(), nullable=False),
    sa.Column('pipeline_duration_s', sa.Float(), nullable=True),
    sa.Column('execution_mode', sa.String(length=20), nullable=True),
    sa.Column('dataset_health', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pipeline_health', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_runs_run_date'), 'daily_runs', ['run_date'], unique=True)
    op.create_table('divergence_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('quant_rank', sa.Integer(), nullable=True),
    sa.Column('agentic_rank', sa.Integer(), nullable=True),
    sa.Column('quant_size', sa.Float(), nullable=False),
    sa.Column('agentic_size', sa.Float(), nullable=False),
    sa.Column('quant_score', sa.Float(), nullable=True),
    sa.Column('agentic_score', sa.Float(), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('quant_baseline_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quant_entry_price', sa.Float(), nullable=True),
    sa.Column('quant_stop_loss', sa.Float(), nullable=True),
    sa.Column('quant_target_1', sa.Float(), nullable=True),
    sa.Column('quant_holding_period', sa.Integer(), nullable=True),
    sa.Column('quant_direction', sa.String(length=10), nullable=True),
    sa.Column('outcome_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divergence_events_run_date'), 'divergence_events', ['run_date'], unique=False)
    op.create_index(op.f('ix_divergence_events_run_id'), 'divergence_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_divergence_events_ticker'), 'divergence_events', ['ticker'], unique=False)
    op.create_table('engine_alert_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alerted_engines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_signature', sa.String(length=500), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_pick_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_name', sa.String(length=30), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('holding_period_days', sa.Integer(), nullable=False),
    sa.Column('is_paper_trade', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('outcome_resolved', sa.Boolean(), nullable=False),
    sa.Column('actual_return_pct', sa.Float(), nullable=True),
    sa.Column('hit_target', sa.Boolean(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('max_favorable_pct', sa.Float(), nullable=True),
    sa.Column('max_adverse_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_name', 'run_date', 'ticker', name='uq_engine_pick_name_date_ticker')
    )
    op.create_index(op.f('ix_engine_pick_outcomes_engine_name'), 'engine_pick_outcomes', ['engine_name'], unique=False)
    op.create_index(op.f('ix_engine_pick_outcomes_run_date'), 'engine_pick_outcomes', ['run_date'], unique=False)
    op.create_index(op.f('ix_engine_pick_outcomes_ticker'), 'engine_pick_outcomes', ['ticker'], unique=False)
    op.create_table('external_engine_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_name', sa.String(length=30), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('picks_count', sa.Integer(), nullable=False),
    sa.Column('ingest_revision', sa.Integer(), nullable=False),
    sa.Column('source_run_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_name', 'run_date', name='uq_engine_result_name_date')
    )
    op.create_index(op.f('ix_external_engine_results_engine_name'), 'external_engine_results', ['engine_name'], unique=False)
    op.create_index(op.f('ix_external_engine_results_run_date'), 'external_engine_results', ['run_date'], unique=False)
    op.create_table('near_misses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.String(length=15), nullable=False),
    sa.Column('debate_verdict', sa.String(length=10), nullable=False),
    sa.Column('net_conviction', sa.Float(), nullable=False),
    sa.Column('bull_conviction', sa.Float(), nullable=True),
    sa.Column('bear_conviction', sa.Float(), nullable=True),
    sa.Column('key_risk', sa.Text(), nullable=True),
    sa.Column('risk_gate_decision', sa.String(length=10), nullable=True),
    sa.Column('risk_gate_reasoning', sa.Text(), nullable=True),
    sa.Column('interpreter_confidence', sa.Float(), nullable=True),
    sa.Column('signal_model', sa.String(length=30), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('timeframe_days', sa.Integer(), nullable=True),
    sa.Column('counterfactual_return', sa.Float(), nullable=True),
    sa.Column('counterfactual_exit_reason', sa.String(length=20), nullable=True),
    sa.Column('outcome_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_near_misses_run_date'), 'near_misses', ['run_date'], unique=False)
    op.create_index(op.f('ix_near_misses_run_id'), 'near_misses', ['run_id'], unique=False)
    op.create_index(op.f('ix_near_misses_ticker'), 'near_misses', ['ticker'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('pnl_dollars', sa.Float(), nullable=True),
    sa.Column('max_favorable', sa.Float(), nullable=True),
    sa.Column('max_adverse', sa.Float(), nullable=True),
    sa.Column('still_open', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=30), nullable=True),
    sa.Column('daily_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partial_exit_price', sa.Float(), nullable=True),
    sa.Column('partial_exit_date', sa.Date(), nullable=True),
    sa.Column('leg2_exit_reason', sa.String(length=20), nullable=True),
    sa.Column('manual_status', sa.String(length=20), nullable=True),
    sa.Column('manual_entry_date', sa.Date(), nullable=True),
    sa.Column('manual_entry_price', sa.Float(), nullable=True),
    sa.Column('manual_exit_date', sa.Date(), nullable=True),
    sa.Column('manual_exit_price', sa.Float(), nullable=True),
    sa.Column('manual_exit_reason', sa.String(length=20), nullable=True),
    sa.Column('manual_pnl_pct', sa.Float(), nullable=True),
    sa.Column('manual_pnl_dollars', sa.Float(), nullable=True),
    sa.Column('entry_slippage_pct', sa.Float(), nullable=True),
    sa.Column('exit_slippage_pct', sa.Float(), nullable=True),
    sa.Column('manual_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_signal_id'), 'outcomes', ['signal_id'], unique=False)
    op.create_table('pipeline_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_artifacts_run_date'), 'pipeline_artifacts', ['run_date'], unique=False)
    op.create_index(op.f('ix_pipeline_artifacts_run_id'), 'pipeline_artifacts', ['run_id'], unique=False)
    op.create_table('shadow_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('parent_track', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_tracks_name'), 'shadow_tracks', ['name'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('signal_model', sa.String(length=30), nullable=False),
    sa.Column('signal_source', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('holding_period_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('interpreter_thesis', sa.Text(), nullable=True),
    sa.Column('debate_summary', sa.Text(), nullable=True),
    sa.Column('risk_gate_decision', sa.String(length=10), nullable=False),
    sa.Column('risk_gate_reasoning', sa.Text(), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_entry_price', sa.Float(), nullable=True),
    sa.Column('also_in_mas', sa.Boolean(), nullable=False),
    sa.Column('suppressed_by_cross_model_ranking', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_run_date'), 'signals', ['run_date'], unique=False)
    op.create_index(op.f('ix_signals_signal_source'), 'signals', ['signal_source'], unique=False)
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('telegram_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chat_id', sa.String(length=30), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_log_sent_at'), 'telegram_log', ['sent_at'], unique=False)
    op.create_index(op.f('ix_telegram_log_source'), 'telegram_log', ['source'], unique=False)
    op.create_table('divergence_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('divergence_id', sa.Integer(), nullable=False),
    sa.Column('agentic_return', sa.Float(), nullable=True),
    sa.Column('agentic_exit_reason', sa.String(length=20), nullable=True),
    sa.Column('quant_return', sa.Float(), nullable=True),
    sa.Column('quant_exit_reason', sa.String(length=20), nullable=True),
    sa.Column('max_adverse_excursion', sa.Float(), nullable=True),
    sa.Column('max_favorable_excursion', sa.Float(), nullable=True),
    sa.Column('return_delta', sa.Float(), nullable=True),
    sa.Column('improved_vs_quant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['divergence_id'], ['divergence_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divergence_outcomes_divergence_id'), 'divergence_outcomes', ['divergence_id'], unique=False)
    op.create_table('engine_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_name', sa.String(length=30), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetch_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('picks_count', sa.Integer(), nullable=True),
    sa.Column('candidates_screened', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('engine_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_result_id'], ['external_engine_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_name', 'run_date', 'attempt', name='uq_engine_run_name_date_attempt')
    )
    op.create_index(op.f('ix_engine_runs_engine_name'), 'engine_runs', ['engine_name'], unique=False)
    op.create_index(op.f('ix_engine_runs_run_date'), 'engine_runs', ['run_date'], unique=False)
    op.create_table('external_engine_result_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_result_id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(length=30), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('picks_count', sa.Integer(), nullable=False),
    sa.Column('source_run_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_result_id'], ['external_engine_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_name', 'run_date', 'revision', name='uq_engine_result_revision_name_date_rev')
    )
    op.create_index(op.f('ix_external_engine_result_revisions_engine_name'), 'external_engine_result_revisions', ['engine_name'], unique=False)
    op.create_index(op.f('ix_external_engine_result_revisions_engine_result_id'), 'external_engine_result_revisions', ['engine_result_id'], unique=False)
    op.create_index(op.f('ix_external_engine_result_revisions_run_date'), 'external_engine_result_revisions', ['run_date'], unique=False)
    op.create_table('position_daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('promising_score', sa.Float(), nullable=False),
    sa.Column('health_state', sa.String(length=10), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('volume_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('regime_score', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_stop_distance', sa.Float(), nullable=True),
    sa.Column('rvol', sa.Float(), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=False),
    sa.Column('score_velocity', sa.Float(), nullable=True),
    sa.Column('signal_regime', sa.String(length=20), nullable=True),
    sa.Column('current_regime', sa.String(length=20), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hard_invalidation', sa.Boolean(), nullable=False),
    sa.Column('invalidation_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'metric_date', name='uq_daily_metric_signal_date')
    )
    op.create_index(op.f('ix_position_daily_metrics_metric_date'), 'position_daily_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_position_daily_metrics_signal_id'), 'position_daily_metrics', ['signal_id'], unique=False)
    op.create_index(op.f('ix_position_daily_metrics_ticker'), 'position_daily_metrics', ['ticker'], unique=False)
    op.create_table('shadow_track_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('holding_period', sa.Integer(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('source_engines', sa.String(length=100), nullable=True),
    sa.Column('outcome_resolved', sa.Boolean(), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('max_favorable', sa.Float(), nullable=True),
    sa.Column('max_adverse', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['shadow_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'run_date', 'ticker', name='uq_shadow_pick_track_date_ticker')
    )
    op.create_index(op.f('ix_shadow_track_picks_run_date'), 'shadow_track_picks', ['run_date'], unique=False)
    op.create_index(op.f('ix_shadow_track_picks_ticker'), 'shadow_track_picks', ['ticker'], unique=False)
    op.create_index(op.f('ix_shadow_track_picks_track_id'), 'shadow_track_picks', ['track_id'], unique=False)
    op.create_table('shadow_track_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_picks', sa.Integer(), nullable=False),
    sa.Column('resolved_picks', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_return_pct', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['shadow_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'snapshot_date', name='uq_shadow_snapshot_track_date')
    )
    op.create_index(op.f('ix_shadow_track_snapshots_snapshot_date'), 'shadow_track_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_shadow_track_snapshots_track_id'), 'shadow_track_snapshots', ['track_id'], unique=False)
    op.create_table('signal_exit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=20), nullable=False),
    sa.Column('signal_model', sa.String(length=30), nullable=False),
    sa.Column('health_state_at_exit', sa.String(length=10), nullable=False),
    sa.Column('promising_score_at_exit', sa.Float(), nullable=False),
    sa.Column('invalidation_reason', sa.String(length=100), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'exit_reason', name='uq_exit_event_signal_reason')
    )
    op.create_index(op.f('ix_signal_exit_events_outcome_id'), 'signal_exit_events', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_signal_exit_events_signal_id'), 'signal_exit_events', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_exit_events_ticker'), 'signal_exit_events', ['ticker'], unique=False)


def downgrade() -> None:
    """Drop the full schema."""
    op.drop_table('signal_exit_events')
    op.drop_table('shadow_track_snapshots')
    op.drop_table('shadow_track_picks')
    op.drop_table('position_daily_metrics')
    op.drop_table('external_engine_result_revisions')
    op.drop_table('engine_runs')
    op.drop_table('divergence_outcomes')
    op.drop_table('telegram_log')
    op.drop_table('signals')
    op.drop_table('shadow_tracks')
    op.drop_table('pipeline_artifacts')
    op.drop_table('outcomes')
    op.drop_table('near_misses')
    op.drop_table('external_engine_results')
    op.drop_table('engine_pick_outcomes')
    op.drop_table('engine_alert_state')
    op.drop_table('divergence_events')
    op.drop_table('daily_runs')
    op.drop_table('candidates')
    op.drop_table('agent_logs')
