"""Add position_daily_metrics and signal_exit_events tables

Revision ID: e9b5089b0025
Revises: 
Create Date: 2026-02-17 10:51:40.056740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b5089b0025'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('promising_score', sa.Float(), nullable=False),
    sa.Column('health_state', sa.String(length=10), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('volume_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('regime_score', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_stop_distance', sa.Float(), nullable=True),
    sa.Column('rvol', sa.Float(), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=False),
    sa.Column('signal_regime', sa.String(length=20), nullable=True),
    sa.Column('current_regime', sa.String(length=20), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hard_invalidation', sa.Boolean(), nullable=False),
    sa.Column('invalidation_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'metric_date', name='uq_daily_metric_signal_date')
    )
    op.create_index(op.f('ix_position_daily_metrics_metric_date'), 'position_daily_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_position_daily_metrics_signal_id'), 'position_daily_metrics', ['signal_id'], unique=False)
    op.create_index(op.f('ix_position_daily_metrics_ticker'), 'position_daily_metrics', ['ticker'], unique=False)
    op.create_table('signal_exit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=20), nullable=False),
    sa.Column('signal_model', sa.String(length=30), nullable=False),
    sa.Column('health_state_at_exit', sa.String(length=10), nullable=False),
    sa.Column('promising_score_at_exit', sa.Float(), nullable=False),
    sa.Column('invalidation_reason', sa.String(length=100), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'exit_reason', name='uq_exit_event_signal_reason')
    )
    op.create_index(op.f('ix_signal_exit_events_outcome_id'), 'signal_exit_events', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_signal_exit_events_signal_id'), 'signal_exit_events', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_exit_events_ticker'), 'signal_exit_events', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_exit_events_ticker'), table_name='signal_exit_events')
    op.drop_index(op.f('ix_signal_exit_events_signal_id'), table_name='signal_exit_events')
    op.drop_index(op.f('ix_signal_exit_events_outcome_id'), table_name='signal_exit_events')
    op.drop_table('signal_exit_events')
    op.drop_index(op.f('ix_position_daily_metrics_ticker'), table_name='position_daily_metrics')
    op.drop_index(op.f('ix_position_daily_metrics_signal_id'), table_name='position_daily_metrics')
    op.drop_index(op.f('ix_position_daily_metrics_metric_date'), table_name='position_daily_metrics')
    op.drop_table('position_daily_metrics')
    # ### end Alembic commands ###
